INSERT INTO t_user (user_id, pw, user_name, email, authority, group_no, user_state)
VALUES
    ('john123', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'John Doe', 'john@example.com', 'admin', FLOOR(1 + RAND() * 10), 'active'),
    ('jane456', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Jane Smith', 'jane@example.com', 'admin', FLOOR(1 + RAND() * 10), 'active'),
    ('mike789', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mike Johnson', 'mike@example.com', 'admin', FLOOR(1 + RAND() * 10), 'active'),
    ('sara101', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Sara Brown', 'sara@example.com', 'admin', FLOOR(1 + RAND() * 10), 'active'),
    ('alex202', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Alex White', 'alex@example.com', 'admin', FLOOR(1 + RAND() * 10), 'active'),
    ('emily303', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emily Lee', 'emily@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('chris404', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Chris Evans', 'chris@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('lisa505', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Lisa Turner', 'lisa@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ryan606', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ryan Harris', 'ryan@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('olivia707', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Olivia Clark', 'olivia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('david808', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'David Hall', 'david@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('emma909', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emma Allen', 'emma@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('jacob010', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Jacob Baker', 'jacob@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mia111', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mia Miller', 'mia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ethan212', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ethan Nelson', 'ethan@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ava313', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ava Roberts', 'ava@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mason414', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mason Walker', 'mason@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('oliver515', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Oliver Scott', 'oliver@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('amelia616', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Amelia Green', 'amelia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mia717', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mia Adams', 'mia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('liam818', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Liam Baker', 'liam@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ava919', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ava Howard', 'ava@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('noah020', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Noah Fisher', 'noah@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mia121', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mia Harris', 'mia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('olivia222', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Olivia James', 'olivia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('jackson323', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Jackson Martinez', 'jackson@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('emma424', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emma Nelson', 'emma@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('oliver525', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Oliver Parker', 'oliver@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ava626', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ava Richardson', 'ava@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mason727', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mason Rogers', 'mason@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('emma828', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emma Smith', 'emma@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('noah929', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Noah Taylor', 'noah@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mia030', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mia Thomas', 'mia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('olivia131', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Olivia Turner', 'olivia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('jackson232', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Jackson Walker', 'jackson@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('emma333', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emma Williams', 'emma@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('liam434', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Liam Wilson', 'liam@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('olivia535', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Olivia Young', 'olivia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ava636', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ava Adams', 'ava@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('noah737', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Noah Baker', 'noah@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mia838', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mia Clark', 'mia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('oliver939', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Oliver Davis', 'oliver@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('emma040', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emma Evans', 'emma@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('jackson141', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Jackson Foster', 'jackson@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('liam242', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Liam Green', 'liam@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('olivia343', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Olivia Hill', 'olivia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ava444', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ava Jackson', 'ava@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('noah545', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Noah Johnson', 'noah@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mia646', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mia King', 'mia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('oliver747', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Oliver Lee', 'oliver@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('emma848', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emma Martin', 'emma@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('jackson949', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Jackson Murphy', 'jackson@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('liam050', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Liam Nelson', 'liam@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('olivia151', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Olivia Parker', 'olivia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ava252', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ava Reed', 'ava@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('noah353', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Noah Richardson', 'noah@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mia454', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mia Roberts', 'mia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('oliver555', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Oliver Robinson', 'oliver@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('emma656', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emma Rogers', 'emma@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('jackson757', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Jackson Ross', 'jackson@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('liam858', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Liam Russell', 'liam@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('olivia959', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Olivia Scott', 'olivia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ava060', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ava Simmons', 'ava@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('noah161', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Noah Stewart', 'noah@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mia262', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mia Taylor', 'mia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('oliver363', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Oliver Thomas', 'oliver@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('emma464', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emma Thompson', 'emma@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('jackson565', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Jackson Turner', 'jackson@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('liam666', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Liam Walker', 'liam@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('olivia767', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Olivia Ward', 'olivia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ava868', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ava Watson', 'ava@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('noah969', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Noah White', 'noah@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mia070', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mia Wood', 'mia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('oliver171', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Oliver Wright', 'oliver@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('emma272', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emma Young', 'emma@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('jackson373', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Jackson Allen', 'jackson@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('liam474', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Liam Adams', 'liam@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('olivia575', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Olivia Brown', 'olivia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ava676', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ava Clark', 'ava@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('noah777', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Noah Davis', 'noah@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mia878', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mia Evans', 'mia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('oliver979', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Oliver Green', 'oliver@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('emma080', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emma Hall', 'emma@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('jackson181', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Jackson Hill', 'jackson@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('liam282', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Liam Jackson', 'liam@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('olivia383', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Olivia James', 'olivia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ava484', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ava Johnson', 'ava@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('noah585', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Noah Lee', 'noah@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mia686', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mia Lewis', 'mia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('oliver787', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Oliver Lopez', 'oliver@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('emma888', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emma Martin', 'emma@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('jackson989', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Jackson Martinez', 'jackson@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('liam090', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Liam Martinez', 'liam@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('olivia191', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Olivia Martin', 'olivia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('ava292', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Ava Martinez', 'ava@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('noah393', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Noah Martinez', 'noah@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('mia494', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Mia Martinez', 'mia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('oliver595', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Oliver Martinez', 'oliver@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('emma696', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Emma Martinez', 'emma@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('jackson797', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Jackson Martinez', 'jackson@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('liam898', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Liam Martinez', 'liam@example.com', 'user', FLOOR(1 + RAND() * 10), 'active'),
    ('olivia999', SUBSTRING(MD5(RAND()) FROM 1 FOR 8), 'Olivia Martinez', 'olivia@example.com', 'user', FLOOR(1 + RAND() * 10), 'active');

INSERT INTO t_group (group_name, group_leader_no, group_state, register_user_no, update_user_no)
VALUES
    ('Marketing Team', 1, 'active', 1, 1),
    ('Sales Team', 2, 'active', 1, 1),
    ('Product Development Team', 3, 'active', 1, 1),
    ('Customer Support Team', 4, 'active', 1, 1),
    ('Finance Team', 5, 'active', 1, 1),
    ('Human Resources Team', 1, 'active', 1, 1),
    ('IT Team', 1, 'active', 1, 1),
    ('Quality Assurance Team', 1, 'active', 1, 1),
    ('Operations Team', 1, 'active', 1, 1),
    ('Research and Development Team', 1, 'active', 1, 1);

INSERT INTO t_article (sharing, content, register_user_no, update_user_no)
VALUES
    ('public', 'This is the content of the first article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the second article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the third article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fourth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fifth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the sixth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the seventh article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eighth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the ninth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the tenth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eleventh article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the twelfth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the thirteenth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fourteenth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fifteenth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the sixteenth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the seventeenth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eighteenth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the nineteenth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the twentieth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the twenty-first article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the twenty-second article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the twenty-third article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the twenty-fourth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the twenty-fifth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the twenty-sixth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the twenty-seventh article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the twenty-eighth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the twenty-ninth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the thirtieth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the thirty-first article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the thirty-second article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the thirty-third article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the thirty-fourth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the thirty-fifth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the thirty-sixth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the thirty-seventh article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the thirty-eighth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the thirty-ninth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fortieth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the forty-first article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the forty-second article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the forty-third article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the forty-fourth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the forty-fifth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the forty-sixth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the forty-seventh article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the forty-eighth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the forty-ninth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fiftieth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fifty-first article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fifty-second article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fifty-third article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fifty-fourth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fifty-fifth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fifty-sixth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fifty-seventh article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fifty-eighth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the fifty-ninth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the sixtieth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the sixty-first article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the sixty-second article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the sixty-third article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the sixty-fourth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the sixty-fifth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the sixty-sixth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the sixty-seventh article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the sixty-eighth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the sixty-ninth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the seventieth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the seventy-first article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the seventy-second article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the seventy-third article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the seventy-fourth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the seventy-fifth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the seventy-sixth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the seventy-seventh article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the seventy-eighth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the seventy-ninth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eightieth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eighty-first article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eighty-second article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eighty-third article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eighty-fourth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eighty-fifth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eighty-sixth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eighty-seventh article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eighty-eighth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the eighty-ninth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the ninetieth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the ninety-first article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the ninety-second article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the ninety-third article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the ninety-fourth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the ninety-fifth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the ninety-sixth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the ninety-seventh article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the ninety-eighth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the ninety-ninth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100)),
    ('public', 'This is the content of the hundredth article.', FLOOR(1 + RAND() * 100), FLOOR(1 + RAND() * 100));
